//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS_BD_IATI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int RecordId { get; set; }
        public string Organization_Id { get; set; }
        public string IATI_Identifier { get; set; }
        public Nullable<System.DateTime> Last_Downloaded { get; set; }
        public Nullable<System.DateTime> Previous_Downloaded { get; set; }
        public string Last_XML { get; set; }
        public string Previous_XML { get; set; }
        public string strLast_XML { get; set; }
        public string strPrevious_XML { get; set; }
        public Nullable<int> Hierarchy { get; set; }
        public Nullable<int> Parent_Hierarchy { get; set; }
    }
}
