//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS_BD_IATI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public string OrgId { get; set; }
        public string IatiIdentifier { get; set; }
        public string IatiActivity { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string IatiActivityPrev { get; set; }
        public Nullable<System.DateTime> DownloadDatePrev { get; set; }
        public Nullable<int> Hierarchy { get; set; }
        public Nullable<int> ParentHierarchy { get; set; }
        public Nullable<bool> IsInclude { get; set; }
        public string AssignedOrgId { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> MappedProjectId { get; set; }
        public Nullable<int> MappedTrustFundId { get; set; }
        public Nullable<bool> IsIgnore { get; set; }
    }
}
