//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS_BD_IATI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIMS_DB_IATIEntities : DbContext
    {
        public AIMS_DB_IATIEntities()
            : base("name=AIMS_DB_IATIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<FieldMappingPreferenceActivity> FieldMappingPreferenceActivities { get; set; }
        public virtual DbSet<FieldMappingPreferenceDelegated> FieldMappingPreferenceDelegateds { get; set; }
        public virtual DbSet<FieldMappingPreferenceGeneral> FieldMappingPreferenceGenerals { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    }
}
