//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS_BD_IATI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchageRateFederal
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Currency { get; set; }
        public string Frequency { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
