//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS_BD_IATI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldMappingPreferenceDelegated
    {
        public long Id { get; set; }
        public byte[] IatiIdentifier { get; set; }
        public string FieldName { get; set; }
        public Nullable<bool> IsInclude { get; set; }
    }
}
