//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS_BD_IATI.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class FieldMappingPreferenceGeneral
    {
        public int Id { get; set; }
        public string OrgId { get; set; }
        public Nullable<int> FundSourceId { get; set; }
        public string FieldName { get; set; }
        public bool IsSourceIATI { get; set; }
    }
}
