//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS_BD_IATI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public Nullable<int> LogType { get; set; }
        public string OrgId { get; set; }
        public string IatiIdentifier { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Message { get; set; }
        public string ExceptionObj { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
