USE [AIMS_DB_Demo]
GO
--2016-12-05
ALTER TABLE tblProjectAttachments ALTER COLUMN AttachmentTitle VARCHAR(2000);
ALTER TABLE tblProjectAttachments ALTER COLUMN AttachmentFileName VARCHAR(2000);
GO

--2016-12-08
ALTER TABLE tblSector ALTER COLUMN IATICode VARCHAR(1000);
ALTER TABLE tblSubSector ALTER COLUMN IATICode VARCHAR(1000);
ALTER TABLE tblThematicMarker ALTER COLUMN IATICode VARCHAR(1000);
GO